interface ImageLinks {
  logo: string;
  menu_icon: string;
  home_img: string;
  about_img: string;
  javascript_logo: string;
  typescript_logo: string;
  react_logo: string;
  nextjs_logo: string;
  css_logo: string;
  tailwind_logo: string;
  vite_logo: string;
  astro_logo: string;
  java_logo: string;
  spring_logo: string;
  node_logo: string;
  mongo_logo: string;
  postgresql_logo: string;
  firebase_logo: string;
  express_logo: string;
  electron_logo: string;
  aws_logo: string;
  bash_logo: string;
  docker_logo: string;
  figma_logo: string;
  git_logo: string;
  jest_logo: string;
  vitest_logo: string;
  playwright_logo: string;
  python_logo: string;
  github_actions_logo: string;
  vercel_logo: string;
  utu_logo: string;
  ctd_logo: string;
  jap_logo: string;
  one_logo: string;
  voxy_logo: string;
  fcc_logo: string;
  ibm_logo: string;
  code_icon: string;
  web_icon: string;
  arrow: string;
  github_icon: string;
  mail_icon: string;
  linkedin_icon: string;
  whatsapp_icon: string;
  logo_sword: string;
}

export const imageLinks: ImageLinks = {
  logo: '/images/logo.png',
  menu_icon: '/images/menu.png',
  home_img: '/images/home_img.jpg',
  about_img: '/images/about.png',
  javascript_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
  typescript_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg',
  react_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg',
  nextjs_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg',
  css_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg',
  tailwind_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg',
  vite_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg',
  astro_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/astro/astro-original.svg',
  java_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg',
  spring_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/spring/spring-original.svg',
  node_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg',
  mongo_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg',
  postgresql_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg',
  firebase_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebase/firebase-original.svg',
  express_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg',
  electron_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/electron/electron-original.svg',
  aws_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
  bash_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bash/bash-original.svg',
  docker_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg',
  figma_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg',
  git_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg',
  jest_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jest/jest-plain.svg',
  vitest_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitest/vitest-original.svg',
  playwright_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/playwright/playwright-original.svg',
  python_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg',
  github_actions_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/githubactions/githubactions-original.svg',
  vercel_logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vercel/vercel-original.svg',
  utu_logo: '/images/utu-logo.png',
  ctd_logo: '/images/ctd-logo.png',
  jap_logo: '/images/jap-logo.png',
  one_logo: '/images/one-logo.png',
  voxy_logo: '/images/voxy-logo.png',
  fcc_logo: '/images/fcc-logo.png',
  ibm_logo: '/images/ibm-logo.png',
  code_icon: '/images/code.png',
  web_icon: '/images/web.png',
  arrow: '/images/arrow.png',
  github_icon: '/images/github.png',
  mail_icon: '/images/mail.png',
  linkedin_icon: '/images/linkedin.png',
  whatsapp_icon: '/images/whatsapp.png',
  logo_sword: '/images/logo_sword.png',
};